version: '3.1'

services:

  db:
    image: postgres
    networks:
      - instagram-network
    restart: always
    container_name: instagram
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: tuandat1601
      POSTGRES_DB: mydatabase
      POSTGRES_USER: tuandat
networks:
      instagram-network: